# Generated by Django 5.2.4 on 2025-07-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
