# Generated by Django 5.2.4 on 2025-07-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_cost_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cultivation_calender',
            name='calender',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='field',
            name='geography',
            field=models.JSONField(default=dict),
        ),
    ]
