# Generated by Django 5.2.4 on 2025-08-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_alter_job_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
