# Generated by Django 5.2.4 on 2025-08-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_cost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='due_date',
            new_name='date',
        ),
    ]
