# Generated by Django 5.2.4 on 2025-07-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_image_comment_alter_cultivation_calender_calender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Irrigating', 'IRRIGATING'), ('Planting', 'PLANTING'), ('PrePlanting', 'PREPLANTING'), ('Fertilizing', 'FERTILIZING'), ('Pruning', 'PRUNING'), ('Harvesting', 'HARVESTING')], default='Irrigating', max_length=15),
        ),
    ]
