# Generated by Django 5.2.4 on 2025-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_rename_due_date_job_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='job',
            name='images',
        ),
        migrations.RemoveField(
            model_name='job',
            name='notes',
        ),
        migrations.AddField(
            model_name='job',
            name='costs',
            field=models.ManyToManyField(blank=True, null=True, to='field.cost'),
        ),
        migrations.AddField(
            model_name='job',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='field.image'),
        ),
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='field.note'),
        ),
    ]
