# Generated by Django 5.2.4 on 2025-07-29 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='Voice',
        ),
        migrations.AlterField(
            model_name='job',
            name='costs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field.cost'),
        ),
        migrations.AlterField(
            model_name='job',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field.image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field.note'),
        ),
        migrations.AlterField(
            model_name='job',
            name='voices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field.voice'),
        ),
        migrations.AddField(
            model_name='voice',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
