# Generated by Django 5.2.4 on 2025-07-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0005_remove_voice_voice_alter_job_costs_alter_job_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='voices',
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Irrigation', 'IRRIGATING'), ('Planting', 'PLANTING'), ('PrePlanting', 'PREPLANTING'), ('Fertilizing', 'FERTILIZING'), ('Spraying', 'SPRAYING'), ('Pruning', 'PRUNING'), ('Harvesting', 'HARVESTING')], default='Irrigating', max_length=15),
        ),
        migrations.DeleteModel(
            name='Voice',
        ),
    ]
